### PR TITLE
Adds psql stuff to fabfile

### PR DESCRIPTION
**Pull request by halfak**
See https://github.com/wiki-ai/wikilabels/pull/57 for the change that adds 'initialized_db' to wikilabels utilities.

### CODE REVIEW

**Comment by he7d3r** [comment]
Looks good to me.

**Comment by yuvipanda** [comment]
If these commands work, then yes, +1 :)

**Comment by yuvipanda** [comment]
Actually wait. -1!

**Comment by yuvipanda** [comment]
This assumes that each web server is also running its own db server, which isn't good. initialize_server should be just initializing a new webserver, IMO - and the db credentials / hostname should be pointed to from a config file.

**Comment by halfak** [comment]
Either way, we'll want to have the staging system pointing at a different DB than the production one.  Not sure how you'd want to handle that.  Maybe we an use /etc/hosts to point wikilabels.db to whatever host (local or other) we need and reference that -- like with redis on ORES. 

Also, the credentials and hostname _do_ come from the config file.

**Comment by yuvipanda** [comment]
Right but the initialize should also be done only once, and the createuser is pointless on a web machine, no? And +1 we can set it up similar to redis.

You'll also want to think of how you're going to do db schema migrations, which are probably going to be a bigger problem. 

I think having the initialize and createuser as part of a initialize_db fab task might be a better idea, and rename current initialize_server to initialize_web_server maybe

**Comment by halfak** [comment]
Hey @yuvipanda.  I see what you mean about not doing the DB init on web server setup.

Re. schema migrations, it seems that is an unrelated problem -- or maybe I am missing something.  Is there a reason we need to solve DB schema migrations in order to set up stage/deploy?

**Comment by yuvipanda** [comment]
Nope - it is an unrelated problem :) was just bringing it up as something
that should be handled at some point, and when we do do that db
initialization might also be part of that, but yes you can ignore that bit
for now :)

On Mon, Jun 29, 2015 at 3:30 PM, Aaron Halfaker notifications@github.com
wrote:

> Hey @yuvipanda https://github.com/yuvipanda. I see what you mean about
> not doing the DB init on web server setup.
> 
> Re. schema migrations, it seems that is an unrelated problem -- or maybe I
> am missing something. Is there a reason we need to solve DB schema
> migrations in order to set up stage/deploy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wiki-ai/wikilabels-wikimedia-config/pull/1#issuecomment-116704799
> .

## 

Yuvi Panda T
http://yuvi.in/blog

**Pull request merged**
