### PR TITLE
Delete "zh" translation for "damaging" form

### PR DESCRIPTION
**Pull request by Artoria2e5**
Currently the "zh" translation takes precedence over simplified (zh-hans) and
traditional (zh-hant) translations defined at TWN.
This file should be removed because:

1. This file is not reliably editable by TWN translators, stopping fixes from coming and showing up.
2. The two scripts of Chinese have visible difference between each other. Unless an auto-converter is deployed in the translation presentation stage, Chinese UI translations should always be split into at least  two variants.

Bug: T162108

### CODE REVIEW

**Comment by liuxinyu970226** [comment]
I'm so sorry for my past wrong translation, thx for pointing and +65535 (i.e. 65535 times of +1)

**Comment by Ladsgroup** [comment]
This should not be merged AFAIK. You need to fix these in translatewiki.net otherwise a bot would rewrite it.

**Comment by liuxinyu970226** [comment]
@Ladsgroup But TWN really doesn't allow /zh translations, to avoid redundant duplications (otherwise, TWN will face-to-face https://phabricator.wikimedia.org/T51898 again)

**Comment by Ladsgroup** [comment]
In that case, go ahead :)

**Pull request merged**
